# Generated by Django 2.2.1 on 2019-10-01 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topictag', '0001_initial'),
        ('organizations', '0004_auto_20190930_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date started')),
                ('active', models.BooleanField(default=True)),
                ('campaign_slug', models.SlugField(max_length=250, unique=True)),
                ('author', models.ManyToManyField(related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='organizations.Organization')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='topictag.TaggedObject', to='topictag.Tag', verbose_name='Tags')),
            ],
        ),
    ]
