# Generated by Django 2.2.1 on 2019-06-02 04:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=144)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExplorePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Explore Post')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('favorite', models.BooleanField(default=False, verbose_name='User favorited')),
                ('liked', models.BooleanField(default=False, verbose_name='Negative sentiment')),
                ('unliked', models.BooleanField(default=False, verbose_name='Negative sentiment')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date started')),
                ('active', models.BooleanField(default=False)),
                ('topic_slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Post content')),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
            ],
        ),
    ]
