# Generated by Django 2.2.1 on 2019-06-02 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topictag', '0001_initial'),
        ('topics', '0001_initial'),
        ('users', '0001_initial'),
        ('organizations', '0002_organization_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AddField(
            model_name='topic',
            name='constituent',
            field=models.ManyToManyField(related_name='_topic_constituent_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='decision_makers',
            field=models.ManyToManyField(related_name='_topic_decision_makers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_topics', to='organizations.Organization'),
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='topictag.TaggedObject', to='topictag.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='explorepost',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_explore_posts', to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='explorepost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_explore_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.UserPost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
