# Generated by Django 2.2.1 on 2019-06-02 04:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_street', models.CharField(max_length=255)),
                ('location_city', models.CharField(max_length=255)),
                ('location_state', models.CharField(max_length=255)),
                ('location_country', models.CharField(max_length=255)),
                ('location_ZIP', models.IntegerField()),
                ('summary', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('org_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('confirmed_identity', models.BooleanField(default=False)),
                ('government', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('org_slug', models.SlugField(max_length=250, unique=True)),
                ('org_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'not specified'), (1, 'city'), (2, 'state'), (3, 'federal'), (4, 'agency'), (5, 'department'), (6, 'company'), (7, 'house'), (8, 'school')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
