# Generated by Django 2.2.1 on 2019-06-02 04:49

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('topictag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='topictag.TaggedObject', to='topictag.Tag', verbose_name='Tags'),
        ),
    ]
