# Generated by Django 2.2.1 on 2019-10-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20190930_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityWiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
